### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Geant200** [karscopsandrobbers/RAGEMP-NativeUI#6]
Bonjour j'ai besoin d'une réponse et je trouve pas dans quelle dossier je de doit installer la Libraries NativeUI sur mon serveur je vous en remerci d'avance.

**Comment by Geant200** [comment]
Hello I need an answer and I can not find in which folder I should install the Libraries NativeUI on my server I thank you in advance.

**Comment by karimcambridge** [comment]
https://github.com/karscopsandrobbers/RAGEMP-NativeUI

Follow the instructions to compile/build it.

Take the compiled file (index.js) and put it in your client scripts and include it.

**Comment by Geant200** [comment]
I receive a message when I issue the following command.  gulp build

[11:41:00] Local modules not found in /home/jeux/grand_theft_auto_5/compileur/nativeui
[11:41:00] Try running: npm install

can you help me ?.

**Comment by karimcambridge** [comment]
run npm i first.
